Code/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('livros/', include('Livro.urls')),
    path('perfil/', include('Perfil.urls')),
    path('leituras/', include('Leitura.urls')),
    path('comentario/', include('Comentario.urls')),
    path('interaçao/', include('Interaçao.urls'))
]

Code/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('livros/', include('Livro.urls')),
    path('perfil/', include('Perfil.urls')),
    path('leituras/', include('Leitura.urls'))
]

Code/mysite/Comentario/models.py
from django.db import models
from Perfil.models import Perfil
from Livro.models import Livro

# Create your models here.
class Comentario(models.Model):
    Conteudo = models.TextField()
    Autor_comentario = models.ForeignKey(Perfil, on_delete=models.PROTECT, related_name='Autor_comentario')
    Livro_comentario = models.ForeignKey(Livro, on_delete=models.PROTECT, related_name='Livro_comentario')
    Data_criaçao = models.DateTimeField(auto_now_add = True)
    Curtida = models.ManyToManyField(Perfil, related_name='Curtida')

Code/mysite/Livro/models.py
from django.db import models

# Create your models here.
class Livro(models.Model):
    Titulo = models.CharField(max_length=1000)
    Editora = models.CharField(max_length=1000)
    Autor = models.CharField(max_length=1000)
    Ano_lancamento = models.CharField(max_length=4)
    Paginas = models.CharField(max_length=10)
    ISBN = models.CharField(max_length=13)
    Categorias = (
        ('Fantasia', 'Fantasia'),
        ('Romance', 'Romance'),
        ('Suspense', 'Suspense'), 
        ('Contos', 'Contos'),
    )
    
    Categoria = models.CharField(max_length=100, choices=Categorias)
    Imagem = models.ImageField(upload_to='static/imagens', null=True, blank=True)
    is_valid = models.BooleanField(default='False')
    #adicionar mais categorias depois 
    Quant_leituras = models.IntegerField(default=0)
    Sinopse = models.TextField()
    
    
    def __str__(self):
        return str(self.Titulo)

Code/mysite/Livro/forms.py
from django import forms 
from .models import Livro

class createLivroForm(forms.ModelForm):
    class Meta:
        model= Livro
        fields = ('Titulo', 'Editora', 'Autor', 'Ano_lancamento', 'Paginas', 'ISBN', 'Categoria', 'Imagem', 'Sinopse')

Code/mysite/Livro/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Avg, Sum
from .forms import createLivroForm
from .models import Livro
from Perfil.models import Perfil
from Leitura.models import Leitura
from Comentario.models import Comentario
from Comentario.forms import createForm
# Create your views here.
@login_required
def criar(request):
    if request.method == "POST":
        form = createLivroForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/livros/')
    else:
        form = createLivroForm()
    
    return render(request,'Livro/criar.html', {'form': form})

@login_required
def listar(request):
    user = request.user
    p = get_object_or_404(Perfil, Usuario=user)
    
    pesquisa = request.GET.get('pesquisa')

    if pesquisa:
        listaLivros = Livro.objects.filter(Titulo__icontains=pesquisa, is_valid='True')
    else:
       listaLivros = Livro.objects.filter(is_valid='True')

    if user.is_superuser:
        return render(request,'Livro/listar-adm.html', {'lista': listaLivros, 'p': p})
    else:
        return render(request,'Livro/listar.html', {'lista': listaLivros, 'p': p})


def listar_solicitacoes(request):
    user = request.user
    p = get_object_or_404(Perfil, Usuario=user)

    pesquisa = request.GET.get('pesquisa')

    if pesquisa:
        listaLivros = Livro.objects.filter(Titulo__icontains=pesquisa, is_valid='False')
    else:
       listaLivros = Livro.objects.filter(is_valid='False')

    return render(request,'Livro/listarSolicitaçoes.html', {'lista': listaLivros, 'p': p})


def validar_solicitaçao(request, id_livro):
    livro = Livro.objects.get (pk=id_livro)
    livro.is_valid = 'True'
    livro.save()
    return redirect('/livros/solicitaçoes/')


@login_required
def expandir(request, id):
    if request.method == "POST":
        form = createForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)

            user = request.user
            f.Autor_comentario = get_object_or_404(Perfil, Usuario=user)
            f.Livro_comentario = get_object_or_404(Livro, pk=id)
            f.save()
            return redirect(reverse('expandir', args=[id])) 
    else:
        form = createForm()

    user = request.user
    p = get_object_or_404(Perfil, Usuario=user)
    livro = Livro.objects.get(pk = id)
    lista_comentarios = Comentario.objects.filter(Livro_comentario = livro).order_by('-Data_criaçao')
    page = request.GET.get('page', 1)
    pagination = Paginator(lista_comentarios, 3)
    page_obj = pagination.get_page(page)
    cont_leituras = Leitura.objects.filter(Livro_lido = livro).count()
    media_avaliacoes = Leitura.objects.filter(Livro_lido = livro).aggregate(Avg('Avaliacao'))['Avaliacao__avg'] or 0
    if user.is_superuser:
        return render(request, 'Livro/detalhes-adm.html', {'page_obj':page_obj, 'livro': livro, 'p': p, 'media_avaliacoes': media_avaliacoes, 'cont_leituras' : cont_leituras, 'lista_comentarios' : lista_comentarios })
    else:
        return render(request, 'Livro/detalhes.html', {'page_obj':page_obj, 'livro': livro, 'p': p, 'media_avaliacoes': media_avaliacoes, 'cont_leituras' : cont_leituras, 'lista_comentarios' : lista_comentarios})
    

@login_required
def editar(request, id):
    livro = Livro.objects.get(pk=id)
    
    if request.method == "POST":
        form = createLivroForm(request.POST, request.FILES, instance=livro)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = createLivroForm(instance=livro)
    
    return render(request, 'Livro/editar.html', {'form': form, 'livro': livro})


@login_required
def deletar(request, id):
    Livro.objects.get(pk=id).delete()
    return redirect("/livros/")

Code/mysite/templates/Livro/criar.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Amor no papel</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray" id="body">
          <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
          <div class="d-flex flex-column justify-content-between">
            <div class="row justify-content-center">
              <div class="col-lg-6 col-xl-5 col-md-10 ">
                <div class="card card-default " style="margin-top: 10px;">
                  <div class="card-header pb-0">
                    <div class="app-brand w-100 d-flex justify-content-center border-bottom-0">
                    </div>
                  </div>
                  <div class="card-body px-5 pb-5 pt-0">
                    <h4 class="text-dark text-center mb-4"  style="margin-top: 25px;">Novo livro</h4>
                    <form method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      <div class="row">
                        <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control input-default"  placeholder="Titulo" name="Titulo" maxlength="1000" required id="id_Titulo">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control input-default"  placeholder="Editora" name="Editora" maxlength="1000" required id="id_Editora">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control input-default"  placeholder="Autor" name="Autor" maxlength="1000" required id="id_Autor">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                          <input type="text" class="form-control input-default"  placeholder="ISBN" name="ISBN" maxlength="13" required id="id_ISBN">
                      </div>
                        <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control input-default"  placeholder="Ano de lançamento" name="Ano_lancamento" maxlength="4" required id="id_Ano_lancamento">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control input-default"  placeholder="Número de páginas" name="Paginas" maxlength="10" required id="id_Paginas">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                            <label for="id_Categoria">Categoria:</label>
                            <select name="Categoria" class="form-control input-default" required id="id_Categoria">
                          <option value="" selected>---------</option>
                        
                          <option value="Fantasia">Fantasia</option>
                        
                          <option value="Romance">Romance</option>
                        
                          <option value="Suspense">Suspense</option>
                        
                          <option value="Contos">Contos</option>
                        
                        </select>
                        </div>
                        <div class="form-group col-md-12 mb-4">
                          <label for="id_Imagem">Selecione uma imagem de perfil</label>
                          <input type="file" class="form-control input-default" id="id_Imagem" name="Imagem">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                          <textarea type="text" class="form-control input-default"  name="Sinopse" placeholder="Digite a sinopse do livro..." cols="1000" rows="10" required id="id_Sinopse"></textarea>
                      </div>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary btn-pill mb-4">Criar Livro</button>

                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

</body>
</html>


Code/mysite/templates/Livro/detalhes-adm.html


{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <title>Amor no papel</title>
  
      <!-- ================= Favicon ================== -->
      <!-- Standard -->
      <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
      <!-- Retina iPad Touch Icon-->
      <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
      <!-- Retina iPhone Touch Icon-->
      <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
      <!-- Standard iPad Touch Icon-->
      <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
      <!-- Standard iPhone Touch Icon-->
      <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
  
      <!-- Styles -->
      <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
      <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray navbar-fixed" id="body">
    <div class="header ml-0  " style="padding-top: 15px;">
      <div class="container-fluid">
          <div class="row">
            <div class="col col-lg-4">
              <img src="/static/imagens/logo.png" height="80px" width="140 px" style="padding-top:0px;">
            </div>
              <div class="col-lg-5">
              </div>
              <div class="col">
                <div class="float-right">
                    <a href="/livros/solicitaçoes/" class="btn btn-lg"><i class="ti-check-box"></i></a>  
                    <a href="/" class="btn btn-lg"><i class="ti-home"></i></a>    
                    <a href="/accounts/logout/"  class="btn btn-lg"><i class="ti-shift-right"></i></a>
                  </div>
              </div>
                  
          </div>
        </div>
    </div>
        <div class="row justify-content-center mt-10" style="margin-top: 10px; margin-left: 100px;  margin-right: 100px;">
            <section id="main-content mt-10">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="card">
                      <div class="card-body">
                        <div class="user-profile">
                          <div class="row">
                            <div class="col-lg-4">
                              <div class="user-photo m-b-30">
                                <img class="img-fluid" src="/{{livro.Imagem}}" width="550" height="300"/>
                              </div>
                            </div>
                            <div class="col-lg-8">
                              <div class="user-profile-name"><h2>{{livro.Titulo}}</h2></div>
                              <div class="user-Location">
                                <i class="ti-location-pin"></i> {{livro.Ano_lancamento}}</div>
                              <div class="ratings">
                                <h4>Ratings</h4>
                                <div class="rating-star">
                                  <span>{{media}}</span>
                                  <i class="ti-star color-primary"></i>
                                  <i class="ti-star color-primary"></i>
                                  <i class="ti-star color-primary"></i>
                                  <i class="ti-star color-primary"></i>
                                  <i class="ti-star"></i>
                                  <span>{{cont}} lidos </span>
                                </div>
                              </div>
                              <div class="user-send-message mt-2">
                                  <a href="/livros/validar/{{livro.id}}"><button type="button" class="btn btn-primary">Validar</button></a>
                                  <a href="/livros/editar/{{livro.id}}"><button type="button" class="btn btn-primary" >Editar</button></a>
                                  <a href="/livros/deletar/{{livro.id}}"><button type="button" class="btn btn-primary" >Deletar</button></a>
                                </div>
                              <div class="custom-tab user-profile-tab mt-5">
                                <ul class="nav nav-tabs" role="tablist">
                                  <li role="presentation" class="active">
                                    <h4>Resumo</h4>
                                  </li>
                                </ul>
                                <div class="tab-content">
                                  <div role="tabpanel" class="tab-pane active" id="1">
                                    <div class="basic-information">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit,m id est laborum.
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /# row -->
              </section>

        </div>
         

  </div>
     </div>
            </div>
        </div>

</body>
</html>


Code/mysite/templates/Livro/editar.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Amor no papel</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray" id="body">
          <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
          <div class="d-flex flex-column justify-content-between">
            <div class="row justify-content-center">
              <div class="col-lg-6 col-xl-5 col-md-10 ">
                <div class="card card-default " style="margin-top: 10px;">
                  <div class="card-header pb-0">
                    <div class="app-brand w-100 d-flex justify-content-center border-bottom-0">
                    </div>
                  </div>
                  <div class="card-body px-5 pb-5 pt-0">
                    <h4 class="text-dark text-center mb-4" style="margin-top: 25px;">Editar livro</h4>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                          <div class="form-group col-md-12 mb-4">
                              <input type="text" class="form-control input-default"  placeholder="Titulo" name="Titulo" maxlength="1000" value="{{livro.Titulo}}" required id="id_Titulo">
                          </div>
                          <div class="form-group col-md-12 mb-4">
                              <input type="text" class="form-control input-default"  placeholder="Editora" name="Editora" maxlength="1000" value="{{livro.Editora}}" required id="id_Editora">
                          </div>
                          <div class="form-group col-md-12 mb-4">
                              <input type="text" class="form-control input-default"  placeholder="Autor" name="Autor" maxlength="1000" value="{{livro.Autor}}" required id="id_Autor">
                          </div>
                          <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control input-default"  placeholder="ISBN" name="ISBN" maxlength="13"  value="{{livro.ISBN}}" required id="id_ISBN">
                        </div>
                          <div class="form-group col-md-12 mb-4">
                              <input type="text" class="form-control input-default"  placeholder="Ano de lançamento" name="Ano_lancamento" value="{{livro.Ano_lancamento}}" maxlength="4" required id="id_Ano_lancamento">
                          </div>
                          <div class="form-group col-md-12 mb-4">
                              <input type="text" class="form-control input-default"  placeholder="Número de páginas" name="Paginas" maxlength="10" value="{{livro.Paginas}}" required id="id_Paginas">
                          </div>
                          {% if livro.Categoria == "Fantasia"%}
                          <div class="form-group col-md-12 mb-4">
                              <label for="id_Categoria">Categoria:</label>
                              <select name="Categoria" class="form-control input-default" required id="id_Categoria">
                            <option value="">---------</option>
                          
                            <option value="Fantasia" selected>Fantasia</option>
                          
                            <option value="Romance">Romance</option>
                          
                            <option value="Suspense">Suspense</option>
                          
                            <option value="Contos">Contos</option>
                          
                          </select>
                          </div>
                          {% elif livro.Categoria == "Romance" %}
                          <div class="form-group col-md-12 mb-4">
                            <label for="id_Categoria">Categoria:</label>
                            <select name="Categoria" class="form-control input-default" required id="id_Categoria">
                          <option value="" >---------</option>
                        
                          <option value="Fantasia">Fantasia</option>
                        
                          <option value="Romance" selected>Romance</option>
                        
                          <option value="Suspense">Suspense</option>
                        
                          <option value="Contos">Contos</option>
                        
                        </select>
                        </div>
                        {% elif livro.Categoria == "Suspense" %}
                          <div class="form-group col-md-12 mb-4">
                            <label for="id_Categoria">Categoria:</label>
                            <select name="Categoria" class="form-control input-default" required id="id_Categoria">
                          <option value="" >---------</option>
                        
                          <option value="Fantasia">Fantasia</option>
                        
                          <option value="Romance">Romance</option>
                        
                          <option value="Suspense" selected>Suspense</option>
                        
                          <option value="Contos">Contos</option>
                        
                        </select>
                        </div>
                        {% elif livro.Categoria == "Contos" %}
                          <div class="form-group col-md-12 mb-4">
                            <label for="id_Categoria">Categoria:</label>
                            <select name="Categoria" class="form-control input-default" required id="id_Categoria">
                          <option value="" >---------</option>
                        
                          <option value="Fantasia">Fantasia</option>
                        
                          <option value="Romance">Romance</option>
                        
                          <option value="Suspense">Suspense</option>
                        
                          <option value="Contos" selected>Contos</option>
                        
                        </select>
                        </div>
                        {% endif %}
                          <div class="form-group col-md-12 mb-4">
                            <label for="id_Imagem">Imagem:</label>
                            Atualmente: <a href="/{{livro.Imagem}}">{{livro.Imagem}}</a>
                            <input type="checkbox" name="Imagem-clear" id="Imagem-clear_id">
                            <label for="Imagem-clear_id">Limpar</label><br>
                             Modificar:
                            <input type="file" name="Imagem" accept="image/*" id="id_Imagem">
                          </div>
                          <div class="form-group col-md-12 mb-4">
                            <textarea type="text" class="form-control input-default"  name="Sinopse" placeholder="Digite a sinopse do livro..." cols="1000" rows="10"  id="id_Sinopse">{{livro.Sinopse}}</textarea>
                        </div>
                          <div class="col-md-12">
                            <button type="submit" class="btn btn-primary btn-pill mb-4">Finalizar</button>
  
                          </div>
                        </div>
                      </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

</body>
</html>