Code/mysite/Leitura/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('criar/<int:id_livro>', views.criar, name='criar'),
    path('', views.listar, name='listar'),
    #path('expandir/<int:id>', views.expandir, name='expandir'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar'),
    path('finalizar/<int:id>', views.finalizar_leitura, name='finalizar_leitura'),
    path('iniciar/<int:id>', views.iniciar_leitura, name='iniciar_leitura'),
    path('lidos/', views.listar_lidos, name='listar_lidos'),
    path('lendo/', views.listar_lendo, name='listar_lendo'),
    path('quero/', views.listar_queroLer, name='listar_queroLer'),
    path('criarMeta/<int:id>', views.meta_leitura, name='meta_leitura'),
    path('editarMeta/<int:id>', views.editarMeta_leitura, name='editarMeta_leitura'),
    path('lidos/<int:id>', views.listar_lidos_visitante, name='listar_lidos_visitante'),
    path('lendo/<int:id>', views.listar_lendo_visitante, name='listar_lendo_visitante'),
    path('quero/<int:id>', views.listar_queroLer_visitante, name='listar_queroLer_visitante'),
    path('<int:id>', views.listar_visitante, name='listar_visitante')
]

Code/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('livros/', include('Livro.urls')),
    path('perfil/', include('Perfil.urls')),
    path('leituras/', include('Leitura.urls')),
    path('comentario/', include('Comentario.urls')),
    path('interaçao/', include('Interaçao.urls'))
]

Code/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('livros/', include('Livro.urls')),
    path('perfil/', include('Perfil.urls')),
    path('leituras/', include('Leitura.urls'))
]

Code/mysite/Leitura/models.py
from django.db import models
from Perfil.models import Perfil
from Livro.models import Livro

# Create your views here.
class Leitura(models.Model):
    STATUS = (
        ('Quero ler', 'Quero ler'),
        ('Lido', 'Lido'), 
        ('Lendo', 'Lendo')
    )
    META = (
        ('Esse mês', 'Esse mês'),
        ('Próximo mês', 'Próximo mês'),
        ('Esse ano', 'Esse ano'),
        ('Próximo ano', 'Próximo ano'),
        ('Não sei', 'Não sei'),
    )
    AVALIAÇAO = (
        (1, 1),
        (1.5, 1.5),
        (2, 2),
        (2.5, 2.5),
        (3, 3), 
        (3.5, 3.5), 
        (4, 4),
        (4.5, 4.5),
        (5, 5)
    )
    Data_inicio = models.DateField(blank = True, null=True)
    Data_final = models.DateField( blank=True, null=True)
    Avaliacao = models.DecimalField(choices=AVALIAÇAO, blank=True, null=True, max_digits=2, decimal_places=1)
    Status = models.CharField(max_length=1000, choices=STATUS)
    Meta_leitura = models.CharField(max_length=1000, choices=META, null=True, blank=True)
    #Favorito = models.BooleanField()
    Leitor = models.ForeignKey(Perfil, on_delete=models.PROTECT, related_name='Leitor')
    Livro_lido = models.ForeignKey(Livro, on_delete=models.PROTECT, related_name='Livro_lido')

    def __str__(self):
        return str(self.Livro_lido)

Code/mysite/Leitura/forms.py
from django import forms 
from .models import Leitura

class createForm(forms.ModelForm):
    class Meta:
        model= Leitura
        fields = ('Status', 'Data_inicio', 'Data_final', 'Avaliacao')

class editarForm(forms.ModelForm):
    class Meta:
        model= Leitura
        fields = ('Status', 'Data_final', 'Avaliacao', 'Meta_leitura', 'Data_inicio')

class createForm_meta(forms.ModelForm):
    class Meta:
        model= Leitura
        fields = ('Meta_leitura',)

Code/mysite/Leitura/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import createForm, createForm_meta, editarForm
from django.core.paginator import Paginator
from .models import Leitura
from Livro.models import Livro 
from Perfil.models import Perfil
from django.utils import timezone
# Create your views here.

@login_required
def criar(request, id_livro):
    if request.method == "POST":
        form = createForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)

            user = request.user
            f.Leitor = get_object_or_404(Perfil, Usuario=user)

            livro = get_object_or_404(Livro, pk=id_livro)
            f.Livro_lido = livro
            livro.Quant_leituras +=1
            livro.save()

            f.save()
            return redirect('/leituras/')
    else:
        form = createForm()
    
    return render(request,'Leitura/criar.html', {'form': form})

@login_required
def listar(request):
    user = request.user
    perfil = get_object_or_404(Perfil, Usuario=user)
    lista = Leitura.objects.filter(Leitor=perfil)
    page = request.GET.get('page', 1)
    pagination = Paginator(lista, 9)
    page_obj = pagination.get_page(page)
    return render(request,'Leitura/listar.html', {'page_obj': page_obj, 'lista': lista,  'p':perfil})


@login_required
def listar_lidos(request):
    user = request.user
    perfil = get_object_or_404(Perfil, Usuario=user)
    lista = Leitura.objects.filter(Leitor=perfil, Status='Lido')
    return render(request,'Leitura/listar_lidos.html', {'lista': lista,  'p':perfil})


@login_required
def listar_lendo(request):
    user = request.user
    perfil = get_object_or_404(Perfil, Usuario=user)
    lista = Leitura.objects.filter(Leitor=perfil, Status='Lendo')
    return render(request,'Leitura/listar_lendo.html', {'lista': lista,  'p':perfil})
   

@login_required
def listar_queroLer(request):
    user = request.user
    perfil = get_object_or_404(Perfil, Usuario=user)
    lista_esseMes = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Esse mês")
    lista_proxMes = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Próximo mês")
    lista_esseAno = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Esse ano")
    lista_proxAno = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Próximo ano")
    lista_naoSei = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Não sei")
    return render(request,'Leitura/listar_queroLer.html', {'lista_esseMes': lista_esseMes, 'lista_proxMes': lista_proxMes, 'lista_esseAno': lista_esseAno, 'lista_proxAno': lista_proxAno, 'lista_naoSei': lista_naoSei, 'p':perfil})

@login_required
def editar(request, id):
    leitura = Leitura.objects.get(pk=id)
    
    if request.method == "POST":
        form = editarForm(request.POST, instance=leitura)
        
        if form.is_valid():
            form.save()
            return redirect("/leituras/")
    else:
        form = editarForm(instance=leitura)
    
    return render(request, 'Leitura/editar.html', {'form': form, 'leitura':leitura})

@login_required
def deletar(request, id):
    leitura = Leitura.objects.get(pk=id)
    livro = get_object_or_404(Livro, pk=leitura.Livro_lido.id)
    livro.Quant_leituras -=1
    livro.save()
    leitura.delete()
    return redirect("/leituras/")

@login_required
def finalizar_leitura(request, id):
    leitura = Leitura.objects.get(pk=id)
    leitura.Data_final = timezone.now()
    leitura.Status = 'Lido'
    leitura.save()
    return redirect("/leituras/")

@login_required
def iniciar_leitura(request, id):
    leitura = Leitura.objects.get(pk=id)
    leitura.Status = 'Lendo'
    leitura.Data_inicio = timezone.now()
    leitura.save()
    return redirect("/leituras/")


@login_required
def meta_leitura(request, id):

    if request.method == "POST":
        form = createForm_meta(request.POST)
        
        if form.is_valid():
            f = form.save(commit=False)

            user = request.user
            f.Leitor = get_object_or_404(Perfil, Usuario=user)
            f.Livro_lido = get_object_or_404(Livro, pk=id)
            f.Status = 'Quero ler'

            f.save()
            return redirect('/')
    else:
        form = createForm_meta()
    
    return render(request,'Leitura/metaLeitura.html', {'form': form})


@login_required
def editarMeta_leitura(request, id):
    leitura = Leitura.objects.get(pk=id)
    
    if request.method == "POST":
        form = editarForm(request.POST, instance=leitura)
        
        if form.is_valid():
            form.save()
            return redirect("/leituras/")
    else:
        form = editarForm(instance=leitura)
    
    return render(request, 'Leitura/editarMeta.html', {'form': form, 'leitura':leitura})


    
@login_required
def listar_visitante(request, id):
    user = request.user
    usuario = get_object_or_404(Perfil, Usuario=user)
    perfil = get_object_or_404(Perfil,id=id)
    lista = Leitura.objects.filter(Leitor=perfil)
    page = request.GET.get('page', 1)
    pagination = Paginator(lista, 9)
    page_obj = pagination.get_page(page)
    return render(request,'Leitura/listarVisitante.html', {'page_obj': page_obj, 'lista': lista,  'p':usuario, 'perfil_visitado':perfil})


@login_required
def listar_lidos_visitante(request, id):
    user = request.user
    usuario = get_object_or_404(Perfil, Usuario=user)
    perfil = get_object_or_404(Perfil,id=id)
    lista = Leitura.objects.filter(Leitor=perfil, Status='Lido')
    return render(request,'Leitura/listar_lidosVisitante.html', {'lista': lista,  'p':usuario, 'perfil_visitado':perfil})


@login_required
def listar_lendo_visitante(request, id):
    user = request.user
    usuario = get_object_or_404(Perfil, Usuario=user)
    perfil = get_object_or_404(Perfil,id=id)
    lista = Leitura.objects.filter(Leitor=perfil, Status='Lendo')
    return render(request,'Leitura/listar_lendoVisitante.html', {'lista': lista,  'p':usuario, 'perfil_visitado':perfil})
   

@login_required
def listar_queroLer_visitante(request, id):
    user = request.user
    usuario = get_object_or_404(Perfil, Usuario=user)
    perfil = get_object_or_404(Perfil,id=id)
    lista_esseMes = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Esse mês")
    lista_proxMes = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Próximo mês")
    lista_esseAno = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Esse ano")
    lista_proxAno = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Próximo ano")
    lista_naoSei = Leitura.objects.filter(Leitor=perfil, Status='Quero ler', Meta_leitura="Não sei")
    return render(request,'Leitura/listar_queroLerVisitante.html', {'lista_esseMes': lista_esseMes, 'lista_proxMes': lista_proxMes, 'lista_esseAno': lista_esseAno, 'lista_proxAno': lista_proxAno, 'lista_naoSei': lista_naoSei, 'p':usuario, 'perfil_visitado':perfil})

Code/mysite/templates/Leitura/criar.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Amor no papel </title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray" id="body">
          <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
          <div class="d-flex flex-column justify-content-between">
            <div class="row justify-content-center">
              <div class="col-lg-6 col-xl-5 col-md-10 ">
                <div class="card card-default mb-0">
                  <div class="card-header pb-0">
                    <div class="app-brand w-100 d-flex justify-content-center border-bottom-0">
                    </div>
                  </div>
                  <div class="card-body px-5 pb-5 pt-0">
                    <h4 class="text-dark text-center mb-4" style="margin-top: 25px;">Nova Leitura</h4>
                    <form method="POST">
                        {% csrf_token %}
                      <div class="row">
                        <div class="form-group col-md-12 mb-4">
                            <label for="id_Status">Status:</label>
                            <select name="Status" class="form-control input-default" required id="id_Status">
                          <option value="" selected>---------</option>
                        
                          <option value="Quero ler">Quero ler</option>
                        
                          <option value="Lido">Lido</option>
                        
                          <option value="Lendo">Lendo</option>
                        
                        </select>
                        </div>
                        <div class="form-group col-md-12 mb-4">
                            <input type="date" class="form-control input-default"   placeholder="Data de inicio"  name="Data_inicio" id="id_Data_inicio">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                            <input type="date" class="form-control input-default"  placeholder="Data final" name="Data_final" id="id_Data_final">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                            <label for="id_Avaliacao">Avaliacao:</label>
                            <select name="Avaliacao" class="form-control input-default"  id="id_Avaliacao">
                          <option value="" selected>---------</option>
                        
                          <option value="1">1</option>
                          <option value="1.5">1,5</option>
                          <option value="2">2</option>
                          <option value="2.5">2,5</option>
                          <option value="3">3</option>
                          <option value="3.5">3,5</option>
                          <option value="4">4</option>
                          <option value="4.5">4,5</option>
                          <option value="5">5</option>
                        
                        </select>
                        </div>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary btn-pill mb-4">Finalizar</button>

                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

</body>
</html>

Code/mysite/templates/Leitura/listar.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Amor no papel</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray" id="body">
    
    <div class="header ml-0  " style="padding-top: 15px;">
      <div class="container-fluid">
          <div class="row">
            <div class="col col-lg-4">
              <img src="/static/imagens/logo.png" height="80px" width="140 px" style="padding-top:0px;">
            </div>
              <div class="col-lg-5">
                
              </div>
                  <div class="float-right">
                    <a href="/" class="btn btn-lg"><i class="ti-home"></i></a>   
                    <a href="/livros/" class="btn btn-lg"><i class="ti-book"></i></a> 
                    <a href="/leituras/" class="btn btn-lg"><i class="ti-bookmark"></i></a> 
                    <a href="/perfil/meuPerfil/" class="btn btn-lg"><i class="ti-user"></i></a>  
                    <a href="/accounts/logout/"  class="btn btn-lg"><i class="ti-shift-right"></i></a>
                  </div>
          </div>
      </div>
  </div>
          <div class="d-flex flex-column justify-content-between">
            <div class="row page-titles mx-0">
              <div class="col p-md-0">
                  <ol class="breadcrumb bg-gray">
                      <li class="breadcrumb-item"><a href="/leituras/">Todas as minhas leituras</a></li>
                      <li class="breadcrumb-item active"><a href="/leituras/lidos">Lidos</a></li>
                      <li class="breadcrumb-item active"><a href="/leituras/lendo">Lendo</a></li>
                      <li class="breadcrumb-item active"><a href="/leituras/quero">Quero ler</a></li>
                  </ol>
              </div>
          </div>
                    <div class="row " style="margin-left: 20px; margin-right:20px;">
                        {% if page_obj %}
                            {% for i in page_obj %}
                            <div class="col-xl-4 col-sm-4">
                              <div class="card card-default card-mini">
                                <div class="card-header bg-white">
                                  <div class="row" >
                                    <div class="col-4">
                                      {% if i.Status == 'Lendo' %}
                                      <div class="alert alert-warning" style="padding: 1px; padding-left: 5px; font-size: small;">
                                        <i class="ti-tag"></i> Lendo
                                      </div>
                                      {% elif i.Status == 'Lido'%}
                                      <div class="alert alert-success" style="padding: 1px; font-size: small;">
                                        <i class="ti-tag"></i> Lido
                                      </div>
                                      {% else %}
                                      <div class="alert alert-primary" style="padding: 1px;  font-size: small;  margin-bottom: 5px;">
                                        <i class="ti-tag"></i> Quero ler
                                      </div>
                                      <div class="alert alert" style="padding: 1px; margin-right: 20px; font-size: small;">
                                        <i class="ti-calendar"></i> {{i.Meta_leitura}}
                                      </div>
                                      {% endif %}
                                    </div>
                                    <div class="col-4"  style="padding: 1px;">
                                      <div class="stat-icon dib"><img class="mr-3" src="/{{i.Livro_lido.Imagem}}" width="115" height="160" alt="">
                                      </div>
                                    </div>
                                  </div>
                                    <div class="row justify-content-center"> 
                                      <div class="col-6">
                                        <div class="row justify-content-center">
                                          <h2>{{i.Livro_lido}}</h2>
                                        </div>
                                      </div>
                                    </div>
                                    <div class="row justify-content-center" style="margin-top: 5px;">
                                      {% if i.Status == 'Lendo' %}
                                      <div class="sub-title">
                                        <span class="mr-1">
                                        <a href="/leituras/editar/{{i.id}}"><button type="button" class="btn btn-outline-secondary">Editar</button></a>
                                        <a href="/leituras/finalizar/{{i.id}}"><button type="button" class="btn btn-outline-secondary">Finalizar</button></a>
                                        <a href="/leituras/deletar/{{i.id}}"><button type="button" class="btn btn-outline-secondary">Deletar</button></a></span> 
                                      </div>
                                      {% elif i.Status == 'Lido'%}
                                      <div class="sub-title">
                                        <span class="mr-1">
                                        <a href="/leituras/editar/{{i.id}}"><button type="button" class="btn btn-outline-secondary">Editar</button></a>
                                        <a href="/leituras/deletar/{{i.id}}"><button type="button" class="btn btn-outline-secondary">Deletar</button></a></span> 
                                      </div>
                                      {% else %}
                                      <div class="sub-title">
                                        <span class="mr-1">
                                          <a href="/leituras/editarMeta/{{i.id}}"><button type="button" class="btn btn-outline-secondary">Editar</button></a>
                                          <a href="/leituras/iniciar/{{i.id}}"><button type="button" class="btn btn-outline-secondary">Iniciar Leitura</button></a>
                                          <a href="/leituras/deletar/{{i.id}}"><button type="button" class="btn btn-outline-secondary">Deletar</button></a></span> 
                                      </div>
                                      {% endif %}
                                     
                                    </div>  
                                </div>    
                              </div>
                            </div>
                            {% endfor %}
                           
                            
                      </div>
                           
                          
                        {% else %}
                            Nenhum livro cadastrado ainda 
                        {% endif %}
                        <div class="row justify-content-center">
                          <div class="bootstrap-pagination">
                            <nav>
                                {% if page_obj.has_other_pages %}
                                <ul class="pagination justify-content-center">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class=" page-item disabled"><span class="page-link" >&laquo;</span></li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class=" page-item active"><span class="page-link" > {{ i }} <span class="sr-only">(current)</span></span></li>
                                        {% else %}
                                            <li class="page-item" ><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item" ><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class=" page-item disabled"><span class="page-link" >&raquo;</span></li>
                                    {% endif %}
                                </ul>
                                {% endif %}
                                </ul>
                            </nav>
                        </div>
                        </div>
                    </div>
                  
                </div>
              </div>
            </div>
        </div>

</body>
</html>


Code/mysite/templates/Leitura/metaLeitura.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Amor no papel</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray" id="body">
          <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
          <div class="d-flex flex-column justify-content-between">
            <div class="row">
              <div class="col-lg-12 col-xl-12 col-md-12 ">
                <div class="card card-default mb-0">
                  <div class="card-body px-5 pb-5 pt-0">
                    <h4 class="text-dark text-center mb-4" style="margin-top: 25px;">Nova Leitura</h4>
                    <form method="POST">
                        {% csrf_token %}
                      <div class="row">
                        <div class="form-group col-md-12 mb-4">
                                <label for="id_Meta_leitura">Quando você pretende ler esse livro?</label>
                                <select name="Meta_leitura" class="form-control input-default" required id="id_Meta_leitura">
                                    <option value="" selected>---------</option>
                                  
                                    <option value="Esse mês">Esse mês</option>
                                  
                                    <option value="Próximo mês">Próximo mês</option>
                                  
                                    <option value="Esse ano">Esse ano</option>
                                  
                                    <option value="Próximo ano">Próximo ano</option>
                                  
                                    <option value="Não sei">Não sei</option>
                                </select>
                        </div>
                        <div class="col-lg-10 col-md-10">
                          <button type="submit" class="btn btn-primary btn-pill mb-4 ">Finalizar</button>

                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

</body>
</html>