Code/mysite/Perfil/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
   path('criar/', views.criar, name='criar'),
   path('listar/<str:pesquisa>', views.listarPerfis, name='listarPerfis'),
   path('visualizar/<int:id>', views.visualizar, name='visualizar'),
   path('editar/<int:id>', views.editar, name='editar'),
   path('meuPerfil/', views.meuPerfil, name='meuPerfil'),
   # path('deletar/<int:id>', views.deletar, name='deletar')

]

Code/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('livros/', include('Livro.urls')),
    path('perfil/', include('Perfil.urls')),
    path('leituras/', include('Leitura.urls')),
    path('comentario/', include('Comentario.urls')),
    path('interaçao/', include('Interaçao.urls'))
]

Code/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('livros/', include('Livro.urls')),
    path('perfil/', include('Perfil.urls')),
    path('leituras/', include('Leitura.urls'))
]

Code/mysite/Perfil/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Perfil(models.Model):
    # Imagem de perfil, genero, telefone(op), cidade, bio
    Nome = models.CharField(max_length=1000)
    Sobrenome = models.CharField(max_length=1000)
    Email = models.EmailField(max_length=256)
    Telefone = models.CharField(max_length=14, null=True, blank=True )
    Cidade = models.CharField(max_length=300, null=True, blank=True )
    Estado = models.CharField(max_length=300, null=True, blank=True )
    Data_nascimento = models.DateField()
    Imagem = models.ImageField(upload_to='static/imagens/fotoUsuario', null=True, blank=True)
    Usuario = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    Generos = (
        ('Masculino', 'Masculino'),
        ('Feminino', 'Feminino'),
    )
    Genero = models.CharField(max_length=100, choices=Generos)
    Bio = models.TextField(max_length=14, null=True, blank=True )
   

Code/mysite/Perfil/forms.py
from django import forms 
from .models import Perfil
class createForm(forms.ModelForm):
    class Meta:
        model= Perfil
        fields = ('Nome', 'Sobrenome', 'Email', 'Data_nascimento', 'Bio', 'Cidade', 'Estado', 'Genero', 'Telefone', 'Imagem' )

class updateForm(forms.ModelForm):
    class Meta:
        model= Perfil
        fields = ('Nome', 'Sobrenome', 'Email', 'Bio', 'Cidade', 'Estado', 'Genero', 'Telefone')

Code/mysite/Perfil/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import createForm, updateForm
from .models import Perfil
from users.views import index
from Comentario.models import Comentario
from Interaçao.models import Interaçao

# Create your views here.
@login_required
def criar(request):
    if request.method == "POST":
        form = createForm(request.POST, request.FILES)
        if form.is_valid():
            perfil = form.save(commit=False)
            perfil.Usuario = request.user
            perfil.save()
            return redirect(reverse('index'))
    else:
        form = createForm()
    
    return render(request,'Perfil/criar.html', {'form': form})


@login_required
def visualizar(request, id):
    
    pesquisa = request.GET.get('pesquisa')
    if pesquisa:
        return redirect(reverse('listarPerfis', args=[pesquisa]))

    perfil = Perfil.objects.get(pk = id)
    user = request.user
    usuario = Perfil.objects.get(Usuario = user)
    segue = Interaçao.objects.filter(Seguidor=usuario, Pessoa_seguida=perfil)
    lista_comentarios = Comentario.objects.filter(Autor_comentario= perfil).order_by('-Data_criaçao')
    page = request.GET.get('page', 1)
    pagination = Paginator(lista_comentarios, 5)
    page_obj = pagination.get_page(page)
    seguidores = Interaçao.objects.filter(Pessoa_seguida=perfil).count()
    seguindo = Interaçao.objects.filter(Seguidor=perfil).count()
    return render(request, 'Perfil/detalhes.html', {'perfil': perfil, 'user':user, 'lista_comentarios':lista_comentarios, 'seguidores':seguidores, 'seguindo': seguindo, 'segue':segue, 'page_obj':page_obj})


@login_required
def meuPerfil(request):
   user = request.user
   perfil = Perfil.objects.get(Usuario=user)
   lista_comentarios = Comentario.objects.filter(Autor_comentario= perfil).order_by('-Data_criaçao')
   page = request.GET.get('page', 1)
   pagination = Paginator(lista_comentarios, 5)
   page_obj = pagination.get_page(page)
   seguidores = Interaçao.objects.filter(Pessoa_seguida=perfil).distinct().count()
   seguindo = Interaçao.objects.filter(Seguidor=perfil).distinct().count()
   return render(request, 'Perfil/meuPerfil.html', {'perfil': perfil, 'page_obj':page_obj, 'user':user, 'lista_comentarios':lista_comentarios, 'seguidores':seguidores, 'seguindo': seguindo})


@login_required
def editar(request, id):
    perfil = Perfil.objects.get(pk=id)
    
    if request.method == "POST":
        form = updateForm(request.POST,  request.FILES, instance=perfil)
        
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = updateForm(instance=perfil)
    
    return render(request, 'Perfil/editar.html', {'form': form, 'perfil': perfil})


def listarPerfis(request, pesquisa):
    lista = Perfil.objects.filter(Nome__icontains=pesquisa)
    page = request.GET.get('page', 1)
    pagination = Paginator(lista, 10)
    page_obj = pagination.get_page(page)

    pesquisa = request.GET.get('pesquisa')
    if pesquisa:
        return redirect(reverse('listarPerfis', args=[pesquisa]))

    return render(request, 'Perfil/listar.html', {'lista':lista, 'page_obj':page_obj})

#def deletar(request, id):
   # Perfil.objects.get(pk=id).delete()
   # return redirect("/")

Code/mysite/templates/Perfil/criar.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Amor no papel</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray" id="body">
          <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
          <div class="d-flex flex-column justify-content-between">
            <div class="row justify-content-center">
              <div class="col-lg-6 col-xl-5 col-md-10 ">
                <div class="card card-default mb-0">
                  <div class="card-header pb-0">
                    <div class="app-brand w-100 d-flex justify-content-center border-bottom-0">
                    </div>
                  </div>
                  <div class="card-body px-5 pb-5 pt-0">
                    <h4 class="text-dark text-center mb-5">Cadastre seu perfil</h4>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                      <div class="row">
                        <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control"  placeholder="Nome" name="Nome" maxlength="1000" required id="id_Nome">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control"  placeholder="Sobrenome" name="Sobrenome" maxlength="1000" required id="id_Sobrenome">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                          <select class="form-control" name="Genero" required id="id_Genero">
                            <option value="" selected>Gênero</option>
                            <option value="Masculino">Masculino</option>
                            <option value="Feminino">Feminino</option>
                          </select>
                       </div>
                        <div class="form-group col-md-12 mb-4">
                            <input class="form-control"  placeholder="Email" type="email" name="Email" maxlength="256" required id="id_Email">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                          <input class="form-control"  placeholder="Telefone" type="text" name="Telefone" maxlength="14" id="id_Telefone">
                      </div>
                        <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control"  placeholder="Data de nascimento" name="Data_nascimento" required id="id_Data_nascimento">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                          <input type="text" class="form-control"  placeholder="Cidade" name="Cidade" maxlength="300" id="id_Cidade">
                      </div>
                      <div class="form-group col-md-12 mb-4">
                        <input type="text" class="form-control"  placeholder="Estado" name="Estado" maxlength="300" id="id_Estado">
                    </div>
                    <div class="form-group col-md-12 mb-4">
                      <label for="id_Imagem">Selecione uma imagem de perfil</label>
                      <input type="file" class="form-control input-default" id="id_Imagem" name="Imagem">
                    </div>
                    <div class="form-group col-md-12 mb-4">
                      <textarea class="form-control" name="Bio" cols="40" rows="2" maxlength="14" id="id_Bio" placeholder="Crie a sua bio"></textarea>
                    </div>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary btn-pill mb-4">Cadastrar</button>

                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

</body>
</html>

Code/mysite/templates/Perfil/detalhes.html

{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <title>Amor no papel</title>
  
      <!-- ================= Favicon ================== -->
      <!-- Standard -->
      <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
      <!-- Retina iPad Touch Icon-->
      <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
      <!-- Retina iPhone Touch Icon-->
      <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
      <!-- Standard iPad Touch Icon-->
      <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
      <!-- Standard iPhone Touch Icon-->
      <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
  
      <!-- Styles -->
      <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
      <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray navbar-fixed" id="body">
    <div class="header ml-0  " style="padding-top: 15px;">
      <div class="container-fluid">
          <div class="row">
            <div class="col col-lg-4">
                <img src="/static/imagens/logo.png" height="80px" width="140 px" style="padding-top:0px;">
              </div>
            <div class="col-lg-5">
                <div class="input-group input-group">
                  <form method='get' class="form-inline my-2 my-lg-0">
                    <input type="text" style="width: 286px;" class="form-control  input-default" placeholder="Pesquisar"  id="pesquisa" name="pesquisa">
                    <span class="input-group-btn" style="height: 45px;"><button class="btn btn-primary btn-group-right" style="height: 45px; width: 58px;" type="submit"><i class="ti-search"></i></button></span>
                  </form>
                </div>
              </div>
              <div class="col">
                <div class="float-right">
                  {% if user.is_superuser %}
                    <a href="/livros/solicitaçoes/" class="btn btn-lg"><i class="ti-check-box"></i></a>  
                  {% endif %}
                  <a href="/" class="btn btn-lg"><i class="ti-home"></i></a>   
                  <a href="/livros/" class="btn btn-lg"><i class="ti-book"></i></a> 
                  <a href="/leituras/" class="btn btn-lg"><i class="ti-bookmark"></i></a> 
                  <a href="/perfil/meuPerfil/" class="btn btn-lg"><i class="ti-user"></i></a>   
                  <a href="/accounts/logout/"  class="btn btn-lg"><i class="ti-shift-right"></i></a>
                </div>
              </div>
                  
          </div>
        </div>
    </div>
    
        <div class="d-flex flex-column justify-content-between" style="margin-top: 10px;">
            <section id="main-content mt-10">
              <div class="container-fluid">
                <div class="row" style="margin-left: 20px; margin-right:20px;">
                    <div class="col-lg-3 col-xl-3" style="padding-right:0px; padding-left:0px;">
                        <div class="card">
                            <div class="card-body">
                                <div class="media align-items-center mb-4">
                                    <img class="mr-3" src="/{{perfil.Imagem}}" width="80" height="80" alt="">
                                    <div class="media-body">
                                        <h3 class="mb-0">{{perfil.Nome}} {{perfil.Sobrenome}}</h3>
                                        <p class="text-muted mb-0"><i class="ti-location-pin"></i> {{perfil.Cidade}}, {{perfil.Estado}}</p>
                                    </div>
                                </div>
                                
                                <div class="row mb-5">
                                    <div class="col">
                                        <div class="card card-profile text-center">
                                            <h3 class="mb-0">{{seguindo}}</h3>
                                            <p class="text-muted px-4">Following</p>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="card card-profile text-center">
                                            <h3 class="mb-0">{{seguidores}}</h3>
                                            <p class="text-muted">Followers</p>
                                        </div>
                                    </div>
                                    {% if segue %}
                                    <div class="col-12 text-center">
                                        <a href="/interaçao/deletar/{{perfil.id}}">
                                            <button class="btn btn-danger px-5">Seguindo</button>
                                        </a>
                                    </div>
                                    {% else %}
                                    <div class="col-12 text-center">
                                        <a href="/interaçao/criar/{{perfil.id}}">
                                            <button class="btn btn-danger px-5">Seguir</button>
                                        </a>
                                    </div>
                                    {% endif %}
                                </div>
          
                                <h4>About Me</h4>
                                <p class="text-muted">{{perfil.Bio}}</p>
                                <ul class="card-profile__info">
                                    <li class="mb-1"><strong class="text-dark mr-4">Mobile</strong> <br> <span>{{perfil.Telefone}}</span></li>
                                    <li><strong class="text-dark mr-4">Email</strong> <br> <span>{{perfil.Email}}</span></li>
                                    <li><strong class="text-dark mr-4">Gênero</strong> <br> <span>{{perfil.Genero}}</span></li>
                                    <li><strong class="text-dark mr-4">Aniversário</strong><br> <span>{{perfil.Data_nascimento}}</span></li>
                                </ul>
                            </div>
                        </div>  
                    </div>
                    <div class="col-lg-7 col-xl-7">
          
                        <div class="card">
                            <div class="card-body">
                              {% for i in page_obj %}
                              <div class="card card-default mb-3">
                                <div class="row">
                                    <div class="col-2">
                                        <a href="/livros/expandir/{{i.Livro_comentario.id}}"><img src="/{{i.Livro_comentario.Imagem}}" class="horizontal-img" alt="Image" width="80" height="100"></a>
                                    </div>
                                    <div class="col-9" style="margin-left:15px;">
                                        <div class="row" style="margin-top:15px;">
                                            <div class="col-10">
                                                <a href="/perfil/visualizar/{{i.Autor_comentario.id}}"><b>{{i.Autor_comentario.Nome}}</b></a> sobre <a  href="/livros/expandir/{{i.Livro_comentario.id}}">{{i.Livro_comentario.Titulo}}</a>
                                            </div>
                                            <div class="col-2 align-items-right">
                                                {{i.Curtida.count}}<a href="/comentario/curtir/{{i.id}}"> <i class="fa fa-thumbs-up"></i></a>
                                            </div>
                                        </div>
                                        <div class="row" style="margin-top:10px; margin-left: 10px;">
                                            {{i.Conteudo}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                               
                            {% endfor %}
          
                        </div>
                        </div>
                        <div class="bootstrap-pagination">
                            <nav>
                                {% if page_obj.has_other_pages %}
                                <ul class="pagination justify-content-center">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class=" page-item disabled"><span class="page-link" >&laquo;</span></li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class=" page-item active"><span class="page-link" > {{ i }} <span class="sr-only">(current)</span></span></li>
                                        {% else %}
                                            <li class="page-item" ><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item" ><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class=" page-item disabled"><span class="page-link" >&raquo;</span></li>
                                    {% endif %}
                                </ul>
                                {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="card">
                            <div class="card-body">
                                <h4> Minhas Leituras</h4>
                                <p class="text-muted"></p>
                                <ul class="card-profile__info">
                                    <li><a href="/leituras/{{perfil.id}}"><span>Todas as leituras</span></a></li>
                                    <li><a href="/leituras/lidos/{{perfil.id}}"><span>Lidos</span></a></li>
                                    <li><a href="/leituras/lendo/{{perfil.id}}"><span>Lendo</span></a></li>
                                    <li><a href="/leituras/quero/{{perfil.id}}"><span>Quero ler</span></a></li>
                                </ul>
                            </div>
                        </div>  
                    </div>
                </div>
            </div>  
                <!-- /# row -->
              </section>

        </div>
         

  </div>
     </div>
            </div>
        </div>

</body>
</html>


Code/mysite/templates/Perfil/editar.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Amor no papel</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray" id="body">
          <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
          <div class="d-flex flex-column justify-content-between">
            <div class="row justify-content-center">
              <div class="col-lg-6 col-xl-5 col-md-10 ">
                <div class="card card-default mb-0">
                  <div class="card-header pb-0">
                    <div class="app-brand w-100 d-flex justify-content-center border-bottom-0">
                    </div>
                  </div>
                  <div class="card-body px-5 pb-5 pt-0">
                    <h4 class="text-dark text-center mb-5">Editar perfil</h4>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">
                          <div class="form-group col-md-12 mb-4">
                              <input type="text" class="form-control"  placeholder="Nome" name="Nome" maxlength="1000" required id="id_Nome" value="{{perfil.Nome}}">
                          </div>
                          <div class="form-group col-md-12 mb-4">
                              <input type="text" class="form-control"  placeholder="Sobrenome" name="Sobrenome" maxlength="1000" required id="id_Sobrenome" value="{{perfil.Sobrenome}}">
                          </div>
                          {% if perfil.Genero == 'Masculino'%}
                              <div class="form-group col-md-12 mb-4">
                                <select class="form-control" name="Genero" required id="id_Genero">
                                  <option value="" >Gênero</option>
                                  <option value="Masculino" selected>Masculino</option>
                                  <option value="Feminino">Feminino</option>
                                </select>
                            </div>
                          {% elif perfil.Genero == 'Feminino' %}
                              <div class="form-group col-md-12 mb-4">
                                <select class="form-control" name="Genero" required id="id_Genero">
                                  <option value="" >Gênero</option>
                                  <option value="Masculino">Masculino</option>
                                  <option value="Feminino"  selected>Feminino</option>
                                </select>
                            </div>
                          {% endif %}
                          <div class="form-group col-md-12 mb-4">
                              <input class="form-control"  placeholder="Email" type="email" name="Email" maxlength="256" required id="id_Email" value="{{perfil.Email}}">
                          </div>
                          <div class="form-group col-md-12 mb-4">
                            <input class="form-control"  placeholder="Telefone" type="text" name="Telefone" maxlength="14" id="id_Telefone" value="{{perfil.Telefone}}">
                        </div>
                          <div class="form-group col-md-12 mb-4">
                            <input type="text" class="form-control"  placeholder="Cidade" name="Cidade" maxlength="300" id="id_Cidade" value="{{perfil.Cidade}}">
                        </div>
                        <div class="form-group col-md-12 mb-4">
                          <input type="text" class="form-control"  placeholder="Estado" name="Estado" maxlength="300" id="id_Estado" value="{{perfil.Estado}}">
                      </div>
                      <div class="form-group col-md-12 mb-4">
                        <textarea class="form-control" name="Bio" cols="40" rows="2" maxlength="14" id="id_Bio" placeholder="Crie a sua bio" value="{{perfil.Bio}}"> {{perfil.Bio}}</textarea>
                      </div>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary btn-pill mb-4">Cadastrar</button>

                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

</body>
</html>