Code/mysite/Comentario/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('criar/<int:id_livro>', views.criar, name='criar'),
    path('', views.listar, name='listar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar'),
    path('curtir/<int:id>', views.curtir, name='curtir')
]

Code/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('livros/', include('Livro.urls')),
    path('perfil/', include('Perfil.urls')),
    path('leituras/', include('Leitura.urls')),
    path('comentario/', include('Comentario.urls')),
    path('interaçao/', include('Interaçao.urls'))
]

Code/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('livros/', include('Livro.urls')),
    path('perfil/', include('Perfil.urls')),
    path('leituras/', include('Leitura.urls'))
]

Code/mysite/Comentario/models.py
from django.db import models
from Perfil.models import Perfil
from Livro.models import Livro

# Create your models here.
class Comentario(models.Model):
    Conteudo = models.TextField()
    Autor_comentario = models.ForeignKey(Perfil, on_delete=models.PROTECT, related_name='Autor_comentario')
    Livro_comentario = models.ForeignKey(Livro, on_delete=models.PROTECT, related_name='Livro_comentario')
    Data_criaçao = models.DateTimeField(auto_now_add = True)
    Curtida = models.ManyToManyField(Perfil, related_name='Curtida')

Code/mysite/Comentario/forms.py
from django import forms 
from .models import Comentario

class createForm(forms.ModelForm):
    class Meta:
        model= Comentario
        fields = ('Conteudo',)

class createForm2(forms.ModelForm):
    class Meta:
        model= Comentario
        fields = ('Conteudo', 'Livro_comentario')

Code/mysite/Comentario/views.py

from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import createForm, createForm2
from .models import Comentario
from Livro.models import Livro 
from Perfil.models import Perfil
from Perfil.views import listarPerfis
from Interaçao.models import Interaçao
from Leitura.models import Leitura
# Create your views here.


@login_required
def criar(request, id_livro):
    if request.method == "POST":
        form = createForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)

            user = request.user
            f.Autor_comentario = get_object_or_404(Perfil, Usuario=user)

            f.save()
            return redirect('/')
    else:
        form = createForm()
    
    return render(request,'Comentario/criar.html', {'form': form})


@login_required
def editar(request, id):
    comentario = Comentario.objects.get(pk=id)
    
    if request.method == "POST":
        form = createForm(request.POST, instance=comentario)
        
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = createForm(instance=comentario)
    
    return render(request, 'Comentario/editar.html', {'form': form, 'comentario':comentario})

@login_required
def listar(request):

    if request.method == "POST":
        form = createForm2(request.POST)
        if form.is_valid():
            f = form.save(commit=False)

            user = request.user
            f.Autor_comentario = get_object_or_404(Perfil, Usuario=user)

            f.save()
            return redirect('/')
    else:
        form = createForm2()
    

    pesquisa = request.GET.get('pesquisa')
    if pesquisa:
        return redirect(reverse('listarPerfis', args=[pesquisa]))


    user = request.user
    perfil = get_object_or_404(Perfil, Usuario=user)
    lista = Comentario.objects.all().order_by('-Data_criaçao')
    page = request.GET.get('page', 1)
    pagination = Paginator(lista, 5)
    page_obj = pagination.get_page(page)
    seguidores = Interaçao.objects.filter(Pessoa_seguida=perfil).distinct().count()
    seguindo = Interaçao.objects.filter(Seguidor=perfil).distinct().count()
    lista_leitura = Leitura.objects.filter(Leitor=perfil, Status='Lido') | Leitura.objects.filter(Leitor=perfil, Status='Lendo')
    top_livros = Livro.objects.all().order_by('-Quant_leituras')[:5]
    return render(request,'Comentario/listar.html', {'page_obj':page_obj, 'lista': lista, 'lista_leitura':lista_leitura, 'top_livros':top_livros,  'p':perfil, 'seguindo':seguindo, 'seguidores':seguidores})


@login_required
def deletar(request, id):
    Comentario.objects.get(pk=id).delete()
    return redirect("/perfil/meuPerfil/")


@login_required
def curtir(request, id):
    u = request.user
    perfil = get_object_or_404(Perfil, Usuario=u)
    comentario = get_object_or_404(Comentario, id=id)
    comentario.Curtida.add(perfil)
    comentario.save()
    return redirect('/')

Code/mysite/templates/Comentario/criar.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Amor no papel </title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray" id="body">
          <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
          <div class="d-flex flex-column justify-content-between">
            <div class="row justify-content-center">
              <div class="col-lg-6 col-xl-5 col-md-10 ">
                <div class="card card-default mb-0">
                  <div class="card-header pb-0">
                    <div class="app-brand w-100 d-flex justify-content-center border-bottom-0">
                    </div>
                  </div>
                  <div class="card-body px-5 pb-5 pt-0">
                    <h4 class="text-dark text-center mb-4" style="margin-top: 25px;">Novo comentário</h4>
                    <form method="POST">
                        {% csrf_token %}
                      <div class="row">
                        <div class="form-group col-md-12 mb-4">
                            <textarea type="text" class="form-control input-default"  name="Conteudo" placeholder="Digite seu comentário..." cols="1000" rows="10" required id="id_Conteudo"></textarea>
                        </div>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary btn-pill mb-4">Finalizar</button>

                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

</body>
</html>

Code/mysite/templates/Comentario/editar.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Amor no papel </title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray" id="body">
          <div class="container d-flex align-items-center justify-content-center" style="min-height: 100vh">
          <div class="d-flex flex-column justify-content-between">
            <div class="row justify-content-center">
              <div class="col-lg-6 col-xl-5 col-md-10 ">
                <div class="card card-default mb-0">
                  <div class="card-header pb-0">
                    <div class="app-brand w-100 d-flex justify-content-center border-bottom-0">
                    </div>
                  </div>
                  <div class="card-body px-5 pb-5 pt-0">
                    <h4 class="text-dark text-center mb-4" style="margin-top: 25px;">Novo comentário</h4>
                    <form method="POST">
                        {% csrf_token %}
                      <div class="row">
                        <div class="form-group col-md-12 mb-4">
                            <textarea type="text" class="form-control input-default" value="{{comentario.Conteudo}}" name="Conteudo"  cols="1000" rows="10" required id="id_Conteudo">{{comentario.Conteudo}}</textarea>
                        </div>
                        <div class="col-md-12">
                          <button type="submit" class="btn btn-primary btn-pill mb-4">Finalizar</button>

                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

</body>
</html>

Code/mysite/templates/Comentario/listar.html

{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <title>Amor no papel </title>
  
      <!-- ================= Favicon ================== -->
      <!-- Standard -->
      <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
      <!-- Retina iPad Touch Icon-->
      <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
      <!-- Retina iPhone Touch Icon-->
      <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
      <!-- Standard iPad Touch Icon-->
      <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
      <!-- Standard iPhone Touch Icon-->
      <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
  
      <!-- Styles -->
      <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
      <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
  <body class="bg-light-gray navbar-fixed" id="body">
    <div class="header ml-0  " style="padding-top: 15px;">
      <div class="container-fluid">
          <div class="row">
            <div class="col col-lg-4">
              <img src="/static/imagens/logo.png" height="80px" width="140 px" style="padding-top:0px;">
            </div>
                          <div class="col-lg-5">
                <div class="input-group input-group">
                  <form method='get' class="form-inline my-2 my-lg-0">
                    <input type="text" style="width: 286px;" class="form-control  input-default" placeholder="Pesquisar"  id="pesquisa" name="pesquisa">
                    <span class="input-group-btn" style="height: 45px;"><button class="btn btn-primary btn-group-right" style="height: 45px; width: 58px;" type="submit"><i class="ti-search"></i></button></span>
                  </form>
                </div>
              </div>
              <div class="col">
                <div class="float-right">
                  {% if user.is_superuser %}
                    <a href="/livros/solicitaçoes/" class="btn btn-lg"><i class="ti-check-box"></i></a>  
                  {% endif %}
                  <a href="/" class="btn btn-lg"><i class="ti-home"></i></a>   
                  <a href="/livros/" class="btn btn-lg"><i class="ti-book"></i></a> 
                  <a href="/leituras/" class="btn btn-lg"><i class="ti-bookmark"></i></a> 
                  <a href="/perfil/meuPerfil/" class="btn btn-lg"><i class="ti-user"></i></a>  
                  <a href="/accounts/logout/"  class="btn btn-lg"><i class="ti-shift-right"></i></a>
                </div>
              </div>
                  
          </div>
        </div>
    </div>
    
        <div class="d-flex flex-column justify-content-between" style="margin-top: 10px;">
            <section id="main-content mt-10">
              <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-lg-3 col-xl-3" style="margin-left: 20px; padding-right:0px; padding-left:0px;">
                        <div class="card">
                            <div class="card-body">
                                <div class="media align-items-center mb-4">
                                    <img class="mr-3" src="/{{p.Imagem}}" width="80" height="80" alt="">
                                    <div class="media-body">
                                        <h3 class="mb-0">{{p.Nome}} {{p.Sobrenome}}</h3>
                                        <p class="text-muted mb-0"><i class="ti-location-pin"></i> {{p.Cidade}}, {{p.Estado}}</p>
                                    </div>
                                </div>
                                
                                <div class="row mb-5">
                                    <div class="col">
                                        <div class="card card-profile text-center">
                                            <h3 class="mb-0">{{seguindo}}</h3>
                                            <p class="text-muted px-4">Following</p>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="card card-profile text-center">
                                            <h3 class="mb-0">{{seguidores}}</h3>
                                            <p class="text-muted">Followers</p>
                                        </div>
                                    </div>
                                    <div class="col-12 text-center">
                                        <a href="/perfil/editar/{{p.id}}">
                                            <button class="btn btn-danger px-5">Editar meu perfil</button>
                                        </a>
                                    </div>
                                </div>
          
                                <h4>About Me</h4>
                                <p class="text-muted">{{p.Bio}}</p>
                                <ul class="card-profile__info">
                                    <li class="mb-1"><strong class="text-dark mr-4">Mobile</strong> <br> <span>{{p.Telefone}}</span></li>
                                    <li><strong class="text-dark mr-4">Email</strong> <br> <span>{{p.Email}}</span></li>
                                    <li><strong class="text-dark mr-4">Gênero</strong> <br> <span>{{p.Genero}}</span></li>
                                    <li><strong class="text-dark mr-4">Aniversário</strong><br> <span>{{p.Data_nascimento}}</span></li>
                                </ul>
                            </div>
                        </div>  
                    </div>
                    <div class="col-lg-5 col-xl-5">
                        <div class="card-body ">
                                <div class="card">
                                    <div class="card-body">
                                        <form method="POST" class="form-profile">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <textarea class="form-control"   required name="Conteudo" id="id_Conteudo" cols="30" rows="2" placeholder="Digite seu comentário..."></textarea>
                                            </div>
                                            Sobre qual livro é o seu comentário?
                                            <div class="d-flex align-items-center">
                                                
                                                <select  class="form-control"  name="Livro_comentario" required id="id_Livro_comentario">
                                                    <option value="" selected>---------</option>
                                                    {% for i in lista_leitura %}
                                                    <option value="{{i.Livro_lido.id}}">{{i.Livro_lido.Titulo}}</option>
                                                    {%endfor%}
                                                  </select>
                                                <button type="submit" class="btn btn-primary px-3 ml-4">Send</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            {% for i in page_obj %}
                            <div class="card card-default mb-3">
                                <div class="row">
                                    <div class="col-2">
                                        <a href="/livros/expandir/{{i.Livro_comentario.id}}"><img src="/{{i.Livro_comentario.Imagem}}" class="horizontal-img" alt="Image" width="80" height="100"></a>
                                    </div>
                                    <div class="col-9" style="margin-left:15px;">
                                        <div class="row" style="margin-top:15px;">
                                            <div class="col-10">
                                                <a href="/perfil/visualizar/{{i.Autor_comentario.id}}"><b>{{i.Autor_comentario.Nome}}</b></a> sobre <a  href="/livros/expandir/{{i.Livro_comentario.id}}">{{i.Livro_comentario.Titulo}}</a>
                                            </div>
                                            <div class="col-2 align-items-right">
                                                {{i.Curtida.count}}<a href="/comentario/curtir/{{i.id}}"> <i class="fa fa-thumbs-up"></i></a>
                                            </div>
                                        </div>
                                        <div class="row" style="margin-top:10px; margin-left: 10px;">
                                            {{i.Conteudo}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                               
                            {% endfor %}
          
                        </div>
                        <div class="bootstrap-pagination">
                            <nav>
                                {% if page_obj.has_other_pages %}
                                <ul class="pagination justify-content-center">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class=" page-item disabled"><span class="page-link" >&laquo;</span></li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class=" page-item active"><span class="page-link" > {{ i }} <span class="sr-only">(current)</span></span></li>
                                        {% else %}
                                            <li class="page-item" ><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item" ><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class=" page-item disabled"><span class="page-link" >&raquo;</span></li>
                                    {% endif %}
                                </ul>
                                {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-lg-3 col-xl-3" style="padding-right:0px; padding-left:0px;">
                        <div class="card">
                            <div class="card-body">
                                <div class="row justify-content-center" style="margin-bottom:20px;">
                                    <h2 class="mb-0">Mais lidos </h2>
                                </div>
                                {% for j in top_livros %}
                                    <div class="media align-items-center mb-4">
                                        <img class="mr-3" src="/{{j.Imagem}}" width="80" height="100" alt="">
                                        <div class="media-body">
                                            <h4 class="mb-0">{{j.Titulo}}</h4>
                                            <p>{{j.Quant_leituras}} Lidos</p>
                                            <a href="/livros/expandir/{{j.id}}"><button type="button" class="btn btn-outline-secondary" style="margin-right:5px;">Visualizar</button></a>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>  
                    </div>
                </div>
            </div>  
                <!-- /# row -->
              </section>

        </div>
         

  </div>
     </div>
            </div>
        </div>

</body>
</html>
